blank_issues_enabled: false
contact_links:
  - name: Questions
    url: https://github.com/israel-dryer/ttkbootstrap/discussions/new
    about: "Ask a question in the discussion forum"
  - name: Documentation
    url: https://ttkbootstrap.readthedocs.io/en/latest/
    about: "ttkbootstrap's documentation"
