name: Feature request
description: Suggest an idea for this project
title: "enter title of enhancement here"
labels: ["enhancement"]
assignees: israel-dryer

body:
  - type: textarea
    id: what
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: |
        "A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]"
    validations:
      required: true

  - type: textarea
    id: extra
    attributes:
      label: "Describe the solution you'd like"
      description: |
        A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: want
    attributes:
      label: "Describe alternatives you've considered"
      description: |
        "A clear and concise description of any alternative solutions or features you've considered."
    validations:
      required: true

  - type: textarea
    id: add
    attributes:
      label: "Additional context"
      description: |
        "Add any other context or screenshots about the feature request here."
    validations:
      required: false
